### ISSUE TITLE
Pop-up windows on 4k display are too small

### ISSUE THREAD

**Issue by nicolasln** [proxeIO/name-panel#6]
I’m not sure this problem is specific to this addon, but on a hi-dpi display the panels are about half the width of a normal display, truncating the UI. It’s still usable but it’s very condensed. Perhaps there’s a way to detect this and scale it appropriately?

Tested on Blender 2.79 RC1 / Windows 10 / Nvidia 1070 / Latest drivers

![hidpi issue](https://user-images.githubusercontent.com/12697664/29319731-f0da5798-81a2-11e7-9c40-4d1554f4498c.png)

**Comment by proxeIO** [comment]
Try using the large pop-up option in the addon preferences, located in user-preferences, addons.
